#!/system/bin/sh

bb=/sbin/bb/busybox

# cpu, sched and cache tweaks
$bb echo 384000 > /sys/devices/system/cpu/cpu0/cpufreq/screen_on_min_freq
$bb echo 537600 > /sys/devices/system/cpu/cpu0/cpufreq/screen_off_max_freq
$bb echo 1228800 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
$bb echo 1 > /sys/devices/system/cpu/cpu0/cpufreq/gpu_oc
$bb echo 2 > /sys/devices/system/cpu/sched_mc_power_savings
$bb echo 15000000 > /proc/sys/kernel/sched_latency_ns
$bb echo 2000000 > /proc/sys/kernel/sched_min_granularity_ns
$bb echo 2500000 > /proc/sys/kernel/sched_wakeup_granularity_ns
$bb echo 0 > /proc/sys/vm/swappiness
$bb echo 55 > /proc/sys/vm/vfs_cache_pressure
$bb echo 0 > /proc/sys/vm/dirty_writeback_centisecs
$bb echo 10240 > /proc/sys/vm/min_free_kbytes
$bb echo 8388608 > /proc/sys/vm/dirty_bytes
$bb echo 2097152 > /proc/sys/vm/dirty_background_bytes

# block tweaks
for i in /sys/block/*/queue ; do
  $bb echo 0 > $i/iostats
  $bb echo 0 > $i/rotational
done

$bb echo 0 > /sys/block/mmcblk0/queue/add_random
$bb echo 2 > /sys/block/mmcblk0/queue/rq_affinity

# adjust f2fs ram threshold
if [ -e /sys/fs/f2fs ] ; then
  $bb echo 5 > /sys/fs/f2fs/mmcblk0p10/ram_thresh
  $bb echo 5 > /sys/fs/f2fs/mmcblk0p11/ram_thresh
  $bb echo 25 > /sys/fs/f2fs/mmcblk0p12/ram_thresh
fi

# enable and setup UKSM
$bb echo 1 > /sys/kernel/mm/uksm/run
$bb echo quiet > /sys/kernel/mm/uksm/cpu_governor
$bb echo 10 > /sys/kernel/mm/uksm/max_cpu_percentage
$bb echo 500 > /sys/kernel/mm/uksm/sleep_millisecs
