#!/system/bin/sh

# wait for systemui to be up
until [ $(pgrep com.android.systemui) ] ; do
  sleep 1
done

# set max cpu freq again because it may have been overwritten by the OS
echo 1228800 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

sleep 5

# decrease max. realtime cpu runtime of background apps
echo 91 > /dev/cpuctl/apps/bg_non_interactive/cpu.shares
echo 400000 > /dev/cpuctl/apps/bg_non_interactive/cpu.rt_runtime_us

# change niceness of systemui
busybox renice -10 -p $(pgrep com.android.systemui)
busybox renice 5 -p $(pgrep flush-)
if [ $? -ne 0 ] ; then
  renice -10 $(pgrep com.android.systemui)
  renice 5 $(pgrep flush-)
fi

# move systemui to the parent task group
echo $(pgrep com.android.systemui) > /dev/cpuctl/tasks

# set cgroup_timer_slack for bg_non_interactive tasks
echo 100000000 > /dev/cpuctl/apps/bg_non_interactive/timer_slack.min_slack_ns

