#!/system/bin/sh

# cpu, sched and cache tweaks
echo 384000 > /sys/devices/system/cpu/cpu0/cpufreq/screen_on_min_freq
echo 537600 > /sys/devices/system/cpu/cpu0/cpufreq/screen_off_max_freq
echo 1228800 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 1 > /sys/devices/system/cpu/cpu0/cpufreq/gpu_oc
echo 2 > /sys/devices/system/cpu/sched_mc_power_savings
echo 15000000 > /proc/sys/kernel/sched_latency_ns
echo 2000000 > /proc/sys/kernel/sched_min_granularity_ns
echo 3000000 > /proc/sys/kernel/sched_wakeup_granularity_ns
echo 92274688 > /proc/sys/vm/dirty_background_bytes
echo 104857600 > /proc/sys/vm/dirty_bytes
echo 35 > /proc/sys/vm/swappiness

# block tweaks
for i in /sys/block/*/queue ; do
  echo 0 > $i/iostats
  echo 0 > $i/rotational
done

echo 2 > /sys/block/mmcblk0/queue/rq_affinity
