#!/system/bin/sh

# execute init.d scripts
run-parts /system/etc/init.d

# wait for system being 'up'
until [ $(pgrep com.android.systemui) ] ; do
  sleep 1
done

# ensure max cpu freq is set properly
echo 1228800 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

# change some processes' cgroups and priorities
sleep 5

echo 91 > /dev/cpuctl/apps/bg_non_interactive/cpu.shares
echo 400000 > /dev/cpuctl/apps/bg_non_interactive/cpu.rt_runtime_us

renice -18 $(pgrep com.android.systemui)
renice 5 $(pgrep kswapd)

echo $(pgrep com.android.systemui) > /dev/cpuctl/tasks

# set cgroup_timer_slack for bg_non_interactive tasks
echo 100000000 > /dev/cpuctl/apps/bg_non_interactive/timer_slack.min_slack_ns

# low memory killer whitelist for common launchers
sleep 20

list="com.cyanogenmod.trebuchet com.android.launcher org.adw.launcher org.adwfreak.launcher com.anddoes.launcher com.gau.go.launcherex com.mobint.hololauncher com.mobint.hololauncher.hd com.teslacoilsw.launcher org.zeam com.chrislacy.actionlauncher.pro com.android.lmt com.tsf.shell com.miui.mihome2 com.qihoo360.launcher com.gtp.nextlauncher net.alamoapps.launcher"

if [ ! -e /data/nowhitelist ] ; then
  for class in $list ; do
    if [ $(pgrep $class) ] ; then
      pid=$(pgrep $class)
      until [ -e /proc/$pid ] ; do
        sleep 1
      done
      echo -17 > /proc/$pid/oom_adj
      break
    fi
  done
fi
